language: python
sudo: false
python:
  - '3.4'
  - '3.5'
install:
  - travis_retry pip install -e .
  - travis_retry pip install file://$(pwd)#egg=log[dev]
  - travis_retry pip install file://$(pwd)#egg=log[arrow]
script:
  - 'py.test --cov log --cov-report term-missing tests'
after_success:
  - coveralls
